version: "3.7"
services:
  nginx:
    build: requirements/nginx
    container_name: nginx
    restart: on-failure
    volumes:
      - type: volume
        source: wordpress
        read_only: true
        target: /app/data
    networks:
      internal:
      local:
        ipv4_address: 192.168.1.2
    depends_on:
      - wordpress
    ports:
     - "443:443"

  mariadb:
    build: requirements/mariadb
    container_name: ${MARIADB_HOST}
    restart: on-failure
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_WP_DB=${MARIADB_WP_DB}
      - MARIADB_WP_USER=${MARIADB_WP_USER}
      - MARIADB_WP_PASSWORD=${MARIADB_WP_PASSWORD}
      - MARIADB_HOST=${MARIADB_HOST}
    volumes:
      - type: volume
        source: mariadb
        target: /app/data
    networks:
      internal:

  wordpress:
    build: requirements/wordpress
    container_name: wordpress
    restart: on-failure
    depends_on:
      - mariadb
      - redis
    environment:
      - MARIADB_WP_DB=${MARIADB_WP_DB}
      - MARIADB_WP_USER=${MARIADB_WP_USER}
      - MARIADB_WP_PASSWORD=${MARIADB_WP_PASSWORD}
      - MARIADB_HOST=${MARIADB_HOST}
      - REDIS_HOST=${REDIS_HOST}
      - WP_ADMIN=${WP_ADMIN}
      - WP_ADMIN_PASSWORD=${WP_ADMIN_PASSWORD}
      - WP_ADMIN_MAIL=${WP_ADMIN_MAIL}
      - WP_TITLE=${WP_TITLE}
      - WP_USER=${WP_USER}
      - WP_USER_PASSWORD=${WP_USER_PASSWORD}
      - WP_USER_MAIL=${WP_USER_MAIL}
    volumes:
      - type: volume
        source: wordpress
        target: /app/data
    networks:
      internal:

  adminer:
    build: requirements/bonus/adminer
    container_name: adminer
    restart: on-failure
    depends_on:
      - mariadb
    volumes:
      - type: volume
        source: adminer
        target: /app/data
    networks:
      internal:

  ftp:
    build: requirements/bonus/ftp
    container_name: ftp
    restart: on-failure
    environment:
      - FTP_USER=${FTP_USER}
      - FTP_PASSWORD=${FTP_PASSWORD}
    volumes:
      - type: volume
        source: wordpress
        target: /app/data
    networks:
      local:
        ipv4_address: 192.168.1.6

  prometheus:
    build: requirements/bonus/prometheus
    container_name: prometheus
    restart: on-failure
    networks:
      local:
        ipv4_address: 192.168.1.7
    ports:
      - "9090:9090"

  redis:
    build: requirements/bonus/redis
    container_name: redis
    restart: on-failure
    networks:
      internal:

  website:
    build: requirements/bonus/website
    container_name: website
    restart: on-failure
    networks:
      local:
        ipv4_address: 192.168.1.8
    ports:
      - "9999:9999"

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/mariadb
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/wordpress
  adminer:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/adminer

networks:
  internal:
  local:
    ipam:
     driver: default
     config:
       - subnet: 192.168.1.0/24
