version: "3.7"
services:
  nginx:
    build: requirements/nginx
    container_name: nginx
    networks:
      local:
        ipv4_address: 192.168.1.4
    ports:
     - 443:443

#  mariadb:
#    restart: always
#    build: requirements/mariadb
#    container_name: mariadb
#    volumes:
#      - type: volume
#        source: mariadb
#        target: /app
#    networks:
#      local:
#        ipv4_address: 192.168.1.2
#
#  wordpress:
#    build: requirements/wordpress
#    container_name: wordpress
#    volumes:
#      - type: volume
#        source: wordpress
#        target: /app 
#    networks:
#      local:
#        ipv4_address: 192.168.1.3

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/mariadb
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/wordpress

networks:
  local:
    ipam:
     driver: default
     config:
       - subnet: "192.168.1.0/24"
