version: "3.7"
services:
  nginx:
    build: requirements/nginx
    container_name: nginx
    volumes:
      - type: volume
        source: wordpress
        read_only: true
        target: /app/data/
    networks:
      local:
        ipv4_address: 192.168.1.4
    ports:
     - "443:443"

  mariadb:
    build: requirements/mariadb
    container_name: ${MARIADB_HOST}
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_WP_DB=${MARIADB_WP_DB}
      - MARIADB_WP_USER=${MARIADB_WP_USER}
      - MARIADB_WP_PASSWORD=${MARIADB_WP_PASSWORD}
      - MARIADB_HOST=${MARIADB_HOST}
    volumes:
      - type: volume
        source: mariadb
        target: /app/data
    networks:
      local:
        ipv4_address: 192.168.1.2
    ports:
      - "3306:3306"

  wordpress:
    build: requirements/wordpress
    container_name: wordpress
    environment:
      - MARIADB_WP_DB=${MARIADB_WP_DB}
      - MARIADB_WP_USER=${MARIADB_WP_USER}
      - MARIADB_WP_PASSWORD=${MARIADB_WP_PASSWORD}
      - MARIADB_HOST=${MARIADB_HOST}
    volumes:
      - type: volume
        source: wordpress
        target: /app/data
    networks:
      local:
        ipv4_address: 192.168.1.3
    ports:
      - "9000:9000"

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/mariadb
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/wordpress

networks:
  local:
    ipam:
     driver: default
     config:
       - subnet: 192.168.1.0/24
